apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  selector:
    matchLabels:
      stack: kompassi
      component: nginx
  template:
    metadata:
      labels:
        stack: kompassi
        component: nginx
    spec:
      affinity: !With
        vars:
          param_component_name: nginx
        template: !Var macro_pod_affinity
      enableServiceLinks: false
      containers:
        - name: master
          image: !Var kompassi_static_image
          ports:
            - containerPort: 80
