# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-03-20 19:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0002_enrollmenteventmeta_override_enrollment_form_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollmenteventmeta',
            name='title',
            field=models.TextField(default='Default enrollment', help_text='Unique title for this enrollment. Examples: Artist alley, cosplay date show, magic wand workshop', verbose_name='Title'),
            preserve_default=False,
        ),
    ]
