# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-04 14:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0003_enrollmenteventmeta_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment',
            name='event',
        ),
        migrations.AddField(
            model_name='enrollmenteventmeta',
            name='slug',
            field=models.TextField(default='default', help_text='Unique machine-readable name for this enrollment. Examples: artistalley, cosplaydateshow, magicwandworkshop.', verbose_name='Slug'),
            preserve_default=False,
        ),
    ]
