apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    stack: kompassi
    component: nginx
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    stack: kompassi
    component: nginx
