apiVersion: apps/v1
kind: Deployment
metadata:
  name: kompassi
spec:
  selector:
    matchLabels:
      stack: kompassi
      component: kompassi
  template:
    metadata:
      labels:
        stack: kompassi
        component: kompassi
    spec:
      affinity: !With
        vars:
          param_component_name: kompassi
        template: !Var macro_pod_affinity
      enableServiceLinks: false
      securityContext: !Var kompassi_pod_security_context
      initContainers:
        - !If
          test: !Var setup_should_run
          then:
            name: setup
            image: !Var kompassi_image
            args: ["python", "manage.py", "setup"]
            env: !Var kompassi_environment
            securityContext: !Var kompassi_container_security_context
      containers:
        - name: master
          image: !Var kompassi_image
          ports:
            - containerPort: 8000
          env: !Var kompassi_environment
          securityContext: !Var kompassi_container_security_context
          args:
            - gunicorn
            - !Format "--workers={kompassi_workers}"
            - --bind=0.0.0.0:8000
            - --access-logfile=-
            - --capture-output
            - !Format "--timeout={kompassi_timeout_seconds}"
            - kompassi.wsgi
          startupProbe: !Var kompassi_startup_probe
          readinessProbe: !Var kompassi_readiness_probe
          livenessProbe: !Var kompassi_liveness_probe
          volumeMounts: !Var kompassi_volume_mounts
      volumes: !Var kompassi_volumes
