apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    stack: kompassi
    component: kompassi
  name: kompassi-media
spec:
  storageClassName: !Var kompassi_storage_pvc_storageclass
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1000Mi
