apiVersion: v1
kind: Service
metadata:
  name: kompassi
  labels:
    stack: kompassi
    component: kompassi
spec:
  ports:
    - port: 8000
      targetPort: 8000
  selector:
    stack: kompassi
    component: kompassi
