name: lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
      - uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - run: uv sync --locked
      - uses: pre-commit/action@v3.0.1

  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-node@v5
        with:
          node-version: 22
          cache: npm
          cache-dependency-path: kompassi-v2-frontend/package-lock.json

      - run: npm ci
        working-directory: kompassi-v2-frontend

      - run: npx eslint src
        working-directory: kompassi-v2-frontend
