apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    stack: kompassi
    component: postgres
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    stack: kompassi
    component: postgres
